package com.example.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.web.socket.config.annotation.EnableWebSocket;
import org.springframework.web.socket.config.annotation.WebSocketConfigurer;
import org.springframework.web.socket.config.annotation.WebSocketHandlerRegistry;
import org.springframework.web.socket.handler.TextWebSocketHandler;
import org.springframework.web.socket.WebSocketSession;
import org.springframework.web.socket.TextMessage;

import java.util.Collections;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

/**
 * WebSocket configuration for Spring Boot.
 * Generated by: kybernus add websocket
 *
 * WebSocket endpoint: ws://localhost:8080/ws
 */
@Configuration
@EnableWebSocket
public class WebSocketConfig implements WebSocketConfigurer {

    @Override
    public void registerWebSocketHandlers(WebSocketHandlerRegistry registry) {
        registry.addHandler(new AppWebSocketHandler(), "/ws")
                .setAllowedOrigins("*");
    }

    static class AppWebSocketHandler extends TextWebSocketHandler {
        private final Set<WebSocketSession> sessions = Collections.newSetFromMap(new ConcurrentHashMap<>());

        @Override
        public void afterConnectionEstablished(WebSocketSession session) throws Exception {
            sessions.add(session);
            session.sendMessage(new TextMessage("{\"event\":\"connected\",\"data\":\"Welcome!\"}"));
        }

        @Override
        protected void handleTextMessage(WebSocketSession session, TextMessage message) throws Exception {
            String payload = message.getPayload();
            session.sendMessage(new TextMessage("{\"event\":\"echo\",\"data\":\"" + payload + "\"}"));
        }

        @Override
        public void afterConnectionClosed(WebSocketSession session, org.springframework.web.socket.CloseStatus status) {
            sessions.remove(session);
        }

        public void broadcast(String message) {
            sessions.forEach(session -> {
                try {
                    session.sendMessage(new TextMessage(message));
                } catch (Exception ignored) {
                }
            });
        }
    }
}
