// Next.js Swagger setup using next-swagger-doc
// File generated by: kybernus add swagger

import { createSwaggerSpec } from 'next-swagger-doc';

export const getSwaggerSpec = () =>
    createSwaggerSpec({
        apiFolder: 'src/app/api',
        definition: {
            openapi: '3.0.0',
            info: {
                title: 'API Documentation',
                version: '1.0.0',
                description: 'Auto-generated API docs by Kybernus',
            },
        },
    });
