// Next.js API route to serve Swagger UI
// Place this file at: src/app/api/docs/route.ts
// File generated by: kybernus add swagger

import { getSwaggerSpec } from '../../../swagger';
import { NextResponse } from 'next/server';

export async function GET() {
    const spec = getSwaggerSpec();
    return NextResponse.json(spec);
}
