/**
 * add.ts
 *
 * `kybernus add [feature]` command.
 * Adds an infrastructure feature (swagger, redis, websocket, husky, auth)
 * to any project — Kybernus-generated or standalone.
 * If `.kybernusrc.json` is not found, prompts for stack + architecture.
 */

import { Command } from 'commander';
import * as clack from '@clack/prompts';
import color from 'picocolors';
import {
    generateFeature,
    getSupportedFeatures,
    SupportedFeature,
    SupportedStack,
} from '../../core/features/feature-generator.js';
import {
    readProjectConfig,
    exitIfCancelled,
    displayFeatureResult,
    handleGenerateError,
    promptArchitecture,
} from '../utils/cli-helpers.js';

const STACK_OPTIONS: { value: SupportedStack; label: string }[] = [
    { value: 'nodejs-express', label: 'Node.js Express' },
    { value: 'nestjs', label: 'NestJS' },
    { value: 'python-fastapi', label: 'Python FastAPI' },
    { value: 'java-spring', label: 'Java Spring Boot' },
    { value: 'nextjs', label: 'Next.js' },
];

export const addCommand = new Command('add')
    .argument('[feature]', 'Feature to add (swagger, redis, websocket, husky, auth)')
    .description('Add infrastructure features to your project')
    .action(async (featureArg?: string) => {
        clack.intro(color.bgCyan(color.black(' kybernus add ')));

        const cwd = process.cwd();

        // Try to read project config — if not found, enter guided wizard mode
        const config = await readProjectConfig(cwd, { requireExistence: false });

        let stack: SupportedStack;
        let architecture: string;

        if (config) {
            stack = config.stack;
            architecture = config.architecture;
            clack.log.info(`Project: ${color.cyan(config.projectName)} (${color.white(stack)})`);
        } else {
            clack.log.warn('No .kybernusrc.json found — this project was not generated by Kybernus.');
            clack.log.info('No problem! Just tell us your stack so we can generate the right files.');

            const selectedStack = await clack.select({
                message: 'What is the stack of this project?',
                options: STACK_OPTIONS,
            });
            exitIfCancelled(selectedStack);
            stack = selectedStack as SupportedStack;

            architecture = await promptArchitecture();
        }

        // --- Resolve feature ---
        const supported = getSupportedFeatures(stack);

        if (supported.length === 0) {
            clack.log.error(`No addable features available for stack "${stack}" yet.`);
            clack.outro(color.red('Nothing added.'));
            process.exit(0);
        }

        let feature = featureArg as SupportedFeature | undefined;

        if (feature && !supported.includes(feature)) {
            clack.log.warn(`Feature "${feature}" is not available for stack "${stack}".`);
            clack.log.info(`Available: ${supported.join(', ')}`);
            process.exit(1);
        }

        if (!feature) {
            const selected = await clack.select({
                message: 'Which feature do you want to add?',
                options: supported.map((f) => ({
                    value: f,
                    label: FEATURE_LABELS[f],
                    hint: FEATURE_HINTS[f],
                })),
            });

            exitIfCancelled(selected);
            feature = selected as SupportedFeature;
        }

        // --- Generate ---
        const spinner = clack.spinner();
        spinner.start(`Adding ${color.cyan(feature)}...`);

        try {
            const result = await generateFeature(feature, stack, cwd, architecture);
            spinner.stop(`${color.green('✅')} Feature "${color.cyan(feature)}" added!`);
            displayFeatureResult(result);
        } catch (err) {
            handleGenerateError(err, spinner);
        }

        clack.outro(color.green('Done! Follow the instructions file to complete the setup.'));
    });

// ─────────────────────────────────────────────────────────────────
// Feature metadata (labels/hints for the interactive picker)
// ─────────────────────────────────────────────────────────────────

const FEATURE_LABELS: Record<SupportedFeature, string> = {
    swagger: 'Swagger / OpenAPI Docs',
    redis: 'Redis Cache',
    websocket: 'WebSocket Server',
    husky: 'Husky + Commitlint',
    auth: 'JWT Authentication',
};

const FEATURE_HINTS: Record<SupportedFeature, string> = {
    swagger: 'Auto-generated API documentation at /api/docs',
    redis: 'Redis client + docker-compose service',
    websocket: 'Real-time WS/socket.io server setup',
    husky: 'Git hooks for linting and conventional commits',
    auth: 'JWT sign/verify, middleware, and password hashing + bcrypt',
};
