/**
 * auth.ts
 * 
 * `kybernus auth` command.
 * Generates a complete, modular JWT authentication flow for the project.
 * Works both in Kybernus-generated projects (reads .kybernusrc.json automatically)
 * and in standalone projects (prompts for stack + architecture).
 */

import { Command } from 'commander';
import * as clack from '@clack/prompts';
import color from 'picocolors';
import { generateFeature, SupportedStack } from '../../core/features/feature-generator.js';
import {
    readProjectConfig,
    exitIfCancelled,
    promptArchitecture,
    displayFeatureResult,
    handleGenerateError,
} from '../utils/cli-helpers.js';

const STACK_OPTIONS: { value: SupportedStack; label: string }[] = [
    { value: 'nodejs-express', label: 'Node.js Express' },
    { value: 'nestjs', label: 'NestJS' },
    { value: 'python-fastapi', label: 'Python FastAPI' },
    { value: 'java-spring', label: 'Java Spring Boot' },
    { value: 'nextjs', label: 'Next.js' },
];

export const authCommand = new Command('auth')
    .description('Add JWT authentication boilerplate to your project')
    .action(async () => {
        clack.intro(color.bgMagenta(color.black(' kybernus auth ')));

        const cwd = process.cwd();

        // Try to read project config; if not found, enter guided wizard mode
        let config = await readProjectConfig(cwd, { requireExistence: false });

        let stack: SupportedStack;
        let architecture: string;

        if (config) {
            // Kybernus project: all info is already known
            stack = config.stack;
            architecture = config.architecture;
            clack.log.info(`Project: ${color.cyan(config.projectName)} (${color.white(stack)} / ${color.white(architecture)})`);
        } else {
            // Standalone project: ask the user for stack + architecture
            clack.log.warn('No .kybernusrc.json found — this project was not generated by Kybernus.');
            clack.log.info('No problem! Answer a couple of questions so we can generate the right files.');

            const selectedStack = await clack.select({
                message: 'What is the stack of this project?',
                options: STACK_OPTIONS,
            });
            exitIfCancelled(selectedStack);
            stack = selectedStack as SupportedStack;

            architecture = await promptArchitecture();
        }

        // Confirm before writing
        const confirm = await clack.confirm({
            message: `Generate JWT auth for ${color.cyan(stack)} (${color.white(architecture)})?`,
        });
        exitIfCancelled(confirm);
        if (!confirm) {
            clack.cancel('Cancelled.');
            process.exit(0);
        }

        // Generate
        const spinner = clack.spinner();
        spinner.start(`Adding JWT auth for ${color.cyan(stack)}...`);

        try {
            const result = await generateFeature('auth', stack, cwd, architecture);
            spinner.stop(`${color.green('✅')} JWT authentication added!`);
            displayFeatureResult(result);
            clack.log.warn(`Don't forget to set ${color.yellow('JWT_SECRET')} in your .env file!`);
        } catch (err) {
            handleGenerateError(err, spinner);
        }

        clack.outro(color.green('Done! Open AUTH.md for the integration guide.'));
    });
