/**
 * deploy.ts
 *
 * `kybernus deploy` command.
 * Generates production-ready deployment configuration files for the chosen
 * cloud provider. Works in Kybernus-generated projects and standalone projects.
 */

import { Command } from 'commander';
import * as clack from '@clack/prompts';
import color from 'picocolors';
import {
    generateDeploy,
    isProviderSupported,
    SupportedProvider,
    SupportedStack,
} from '../../core/deploy/deploy-generator.js';
import {
    readProjectConfig,
    exitIfCancelled,
} from '../utils/cli-helpers.js';

// ─────────────────────────────────────────────────────────────────
// Metadata
// ─────────────────────────────────────────────────────────────────

const PROVIDER_OPTIONS: { value: SupportedProvider; label: string; hint: string }[] = [
    { value: 'vercel', label: 'Vercel', hint: 'Great for Next.js, Node.js, and Python — zero-config' },
    { value: 'railway', label: 'Railway', hint: 'Supports all stacks — easy Postgres provisioning' },
    { value: 'fly', label: 'Fly.io', hint: 'Supports all stacks — runs Docker containers globally' },
    { value: 'render', label: 'Render', hint: 'Supports all stacks — generous free tier' },
];

const STACK_OPTIONS: { value: SupportedStack; label: string }[] = [
    { value: 'nodejs-express', label: 'Node.js Express' },
    { value: 'nestjs', label: 'NestJS' },
    { value: 'python-fastapi', label: 'Python FastAPI' },
    { value: 'java-spring', label: 'Java Spring Boot' },
    { value: 'nextjs', label: 'Next.js' },
];

// ─────────────────────────────────────────────────────────────────
// Command
// ─────────────────────────────────────────────────────────────────

export const deployCommand = new Command('deploy')
    .description('Generate deployment configuration files for cloud providers')
    .action(async () => {
        clack.intro(color.bgBlue(color.white(' kybernus deploy ')));

        const cwd = process.cwd();
        const config = await readProjectConfig(cwd, { requireExistence: false });

        let stack: SupportedStack;

        if (config) {
            stack = config.stack as SupportedStack;
            clack.log.info(`Project: ${color.cyan(config.projectName)} (${color.white(stack)})`);
        } else {
            clack.log.warn('No .kybernusrc.json found — this project was not generated by Kybernus.');
            clack.log.info('No problem! Just tell us your stack.');

            const selectedStack = await clack.select({
                message: 'What is the stack of this project?',
                options: STACK_OPTIONS,
            });
            exitIfCancelled(selectedStack);
            stack = selectedStack as SupportedStack;
        }

        // --- Select provider ---
        const supportedProviders = PROVIDER_OPTIONS.filter((p) =>
            isProviderSupported(p.value, stack)
        );

        if (supportedProviders.length === 0) {
            clack.log.error(`No supported cloud providers found for stack "${stack}".`);
            process.exit(1);
        }

        const selectedProvider = await clack.select({
            message: 'Which cloud provider do you want to deploy to?',
            options: supportedProviders.map((p) => ({
                value: p.value,
                label: p.label,
                hint: p.hint,
            })),
        });
        exitIfCancelled(selectedProvider);
        const provider = selectedProvider as SupportedProvider;

        // --- Ask about Dockerfile (providers that use containers) ---
        const PROVIDERS_WITH_DOCKERFILE: SupportedProvider[] = ['railway', 'fly', 'render'];
        let includeDockerfile = false;

        if (PROVIDERS_WITH_DOCKERFILE.includes(provider)) {
            const dockerAnswer = await clack.confirm({
                message: `Include a ${color.yellow('Dockerfile')}? ${color.dim('(skip if your project already has one)')}`,
                initialValue: false,
            });
            exitIfCancelled(dockerAnswer);
            includeDockerfile = dockerAnswer as boolean;
        }

        // --- Confirm ---
        const confirm = await clack.confirm({
            message: `Generate ${color.cyan(provider)} deployment config for ${color.cyan(stack)}?`,
        });
        exitIfCancelled(confirm);
        if (!confirm) {
            clack.cancel('Cancelled.');
            process.exit(0);
        }

        // --- Generate ---
        const spinner = clack.spinner();
        spinner.start(`Generating ${color.cyan(provider)} config...`);

        try {
            const result = await generateDeploy(provider, stack, cwd, includeDockerfile);
            spinner.stop(`${color.green('✅')} Deploy config generated!`);

            clack.log.step('Files created:');
            for (const file of result.copiedFiles) {
                clack.log.info(`  ${color.dim('→')} ${file}`);
            }

            if (result.instructionsPath) {
                clack.log.step(`📖 Deployment guide: ${color.yellow(result.instructionsPath)}`);
            }
        } catch (err: unknown) {
            spinner.stop();
            clack.log.error(`❌ ${err instanceof Error ? err.message : String(err)}`);
            process.exit(1);
        }

        clack.outro(color.green('Done! Open DEPLOY.md for the next steps.'));
    });
